DROP TABLE IF EXISTS tutorial.user;

CREATE TABLE IF NOT EXISTS tutorial.USER (
	USER_NAME 					VARCHAR(20) NOT NULL,
	FIRST_NAME 					VARCHAR(50) NOT NULL,
	SECOND_NAME 				VARCHAR(50) NOT NULL DEFAULT '',
	SURNAME						VARCHAR(50) NOT NULL,
	BIRTH_DATE					DATE NOT NULL,
	BIRTH_GENDER				ENUM ('M', 'F') NOT NULL,
	CREATION_TIMESTAMP			TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LAST_MODIFICATION_TIMESTAMP	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	DELETION_TIMESTAMP			TIMESTAMP NULL,
	
	PRIMARY KEY (USER_NAME)
) CHARACTER SET utf8mb4;
